app:
  name: "user-service"
  version: "1.0.0"
  debug: true
  environment: "development"

logger:
  level: "debug"
  enable_caller: false
  enable_trace: false

server:
  host: "0.0.0.0"
  port: 8083
